# Generated by Django 2.2.6 on 2019-10-14 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191013_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='author',
            new_name='created_by',
        ),
    ]
